[package]
name = "pfm"
version = "0.1.0"
edition = "2018"

[features]
rt = ["cortex-m-rt/device"]

[dependencies]
cortex-m = "0.7"
vcell = "0.1.2"
cortex-m-rt = { version = "0.6",  optional = true }

[[bin]]
name = "main"
path = "bin/main.rs"
